site_name: learn docker the hard way
site_author: luw2007@gmail.com

theme: readthedocs
dev_addr: 0.0.0.0:8000

pages:
- [index.md, 说明]
- [Part1/0_docker-v0.1.0.md,  第一部分, 0. 目录结构]
- [Part1/1_docker.go.md,      第一部分, 1. 介绍docker.go]
- [Part1/2_runtime.go.md,     第一部分, 2. 介绍runtime.go]
- [Part1/3_graph.go.md,       第一部分, 3. 介绍graph.go]
- [Part1/4_tags.go.md,        第一部分, 4. 介绍tags.go]
- [Part1/5_network.go.md,     第一部分, 5. 介绍network.go]
- [Part1/6_image.go.md,       第一部分, 6. 介绍image.go]
- [Part1/7_container.go.md,   第一部分, 7. 介绍container.go]
- [Part1/8_mount.go.md,       第一部分, 8. 介绍mount.go]
- [Part1/9_auth.go.md,        第一部分, 9. 介绍auth.go]
- [Part1/10_sysinit.go.md,    第一部分,10. 介绍sysinit.go]
- [Part1/11_state.go.md,      第一部分,11. 介绍state.go]
- [Part1/12_commands.go.md,   第一部分,12. 介绍commands.go]
- [named.md, 对照表]