site_name: learn docker the hard way
site_author: luw2007@gmail.com

theme: readthedocs
dev_addr: 0.0.0.0:8000

pages:
- [index.md, 说明]
- [Part1/0_docker-v0.1.0.md,  第一部分, 0. 目录结构]
- [Part1/1_docker.go.md,      第一部分, 1. 介绍docker.go]
- [Part1/2_runtime.go.md,     第一部分, 2. 介绍runtime.go]
- [Part1/3_graph.go.md,       第一部分, 3. 介绍graph.go]
- [Part1/4_tags.go.md,        第一部分, 4. 介绍tags.go]
- [Part1/5_network.go.md,     第一部分, 5. 介绍network.go]
- [Part1/6_image.go.md,       第一部分, 6. 介绍image.go]
- [named.md, 对照表]