site_name: learn docker the hard way
site_author: luw2007@gmail.com

theme: readthedocs
dev_addr: 0.0.0.0:8000

pages:
- [index.md, 说明]
- [Part1/0_docker-v0.1.0.md,  第一部分, 目录结构]
- [Part1/1_docker.go.md,      第一部分, docker.go]
- [Part1/2_runtime.go.md,     第一部分, runtime.go]